"""
Docker Sandbox — run tests inside an isolated container.

Why:
    Tests run arbitrary code generated by an LLM. Running them directly
    on the host is a security risk: infinite loops block the agent,
    file system writes could escape the workspace, and network calls
    could leak data. A Docker container enforces hard limits.

Architecture (WSL path):
    Windows Python (uvicorn)
        → subprocess.run(["wsl", "docker", "run", ...])
            → container: python:3.12-slim
                → pytest inside /workspace (read-write mount)
            → stdout/stderr captured
        → returncode returned to testgeneer

Security guarantees:
    --network=none     No internet access from inside container
    --memory=512m      OOM-killed if LLM generates a memory bomb
    --cpus=1           No CPU starvation of host
    --read-only + tmpfs  Only /workspace and /tmp are writable
    --rm               Container deleted immediately after exit
    --no-new-privileges  Cannot escalate to root

WSL path translation:
    D:\\ageneers\\workspaces\\TASK-1-abc  →  /mnt/d/ageneers/workspaces/TASK-1-abc
"""

from __future__ import annotations

import os
import re
import subprocess
import sys
from pathlib import Path

from app.utils.logger import get_logger

logger = get_logger(__name__)

# ─────────────────────────────────────────────────────────────────────────────
# Config
# ─────────────────────────────────────────────────────────────────────────────

DOCKER_IMAGE   = os.getenv("DOCKER_SANDBOX_IMAGE", "ageneers-sandbox:latest")
DOCKER_MEMORY  = os.getenv("DOCKER_SANDBOX_MEMORY", "512m")
DOCKER_CPUS    = os.getenv("DOCKER_SANDBOX_CPUS", "1")
DOCKER_TIMEOUT = int(os.getenv("DOCKER_SANDBOX_TIMEOUT", "120"))  # seconds

# How to invoke docker — "wsl" for WSL, "docker" for native
DOCKER_CMD = os.getenv("DOCKER_CMD", "wsl" if sys.platform == "win32" else "docker")


# ─────────────────────────────────────────────────────────────────────────────
# Path translation
# ─────────────────────────────────────────────────────────────────────────────

def _windows_to_wsl_path(path: str) -> str:
    """
    Convert a Windows absolute path to its WSL /mnt/X/... equivalent.

    Examples:
        D:\\ageneers\\workspaces\\TASK-1  →  /mnt/d/ageneers/workspaces/TASK-1
        C:\\Users\\foo                    →  /mnt/c/Users/foo
    """
    # Normalise separators
    path = path.replace("\\", "/")

    # Match drive letter: D:/foo/bar
    match = re.match(r"^([A-Za-z]):/(.*)$", path)
    if match:
        drive  = match.group(1).lower()
        rest   = match.group(2)
        return f"/mnt/{drive}/{rest}"

    # Already a Unix path — return as-is
    return path


def _get_wsl_workspace_path(workspace: Path) -> str:
    """Return the WSL-accessible path for the given workspace."""
    if sys.platform == "win32":
        return _windows_to_wsl_path(str(workspace))
    return str(workspace)     # Linux/macOS — no conversion needed


# ─────────────────────────────────────────────────────────────────────────────
# Dependency installer
# ─────────────────────────────────────────────────────────────────────────────

def _get_install_cmd(workspace_wsl: str) -> list[str]:
    """
    Build a shell command that installs workspace dependencies before pytest.
    Tries requirements.txt first, then pyproject.toml.
    """
    return [
        "sh", "-c",
        (
            "pip install --quiet --no-cache-dir fastapi httpx pydantic pytest pytest-asyncio 2>/dev/null; "
            f"if [ -f {workspace_wsl}/requirements.txt ]; then "
            f"  pip install --quiet --no-cache-dir -r {workspace_wsl}/requirements.txt 2>/dev/null; "
            f"elif [ -f {workspace_wsl}/pyproject.toml ]; then "
            f"  pip install --quiet --no-cache-dir {workspace_wsl} 2>/dev/null || true; "
            f"fi; "
            f"cd {workspace_wsl} && pytest --rootdir={workspace_wsl} --override-ini=addopts= -p no:cacheprovider"
        )
    ]


# ─────────────────────────────────────────────────────────────────────────────
# Public API
# ─────────────────────────────────────────────────────────────────────────────

def is_docker_available() -> bool:
    """
    Quick check: can we reach the Docker daemon?
    Returns False gracefully so testgeneer can fall back to host execution.
    """
    try:
        cmd = ["wsl", "docker", "info"] if DOCKER_CMD == "wsl" else ["docker", "info"]
        result = subprocess.run(
            cmd,
            capture_output=True,
            timeout=10,
        )
        return result.returncode == 0
    except Exception:
        return False


def run_tests_in_sandbox(
    workspace: Path,
    timeout: int = DOCKER_TIMEOUT,
) -> tuple[int, str]:
    """
    Run pytest inside a Docker container and return (returncode, output).

    The container:
      - Has no network access
      - Is limited to 512 MB RAM and 1 CPU
      - Only has read-write access to /workspace and /tmp
      - Is automatically removed after exit

    Args:
        workspace: absolute path to the cloned repo workspace
        timeout:   seconds before the container is force-killed

    Returns:
        (returncode, combined_stdout_stderr)
    """
    wsl_workspace = _get_wsl_workspace_path(workspace)

    # Build the docker run command
    if DOCKER_CMD == "wsl":
        docker_base = ["wsl", "docker"]
    else:
        docker_base = ["docker"]

    cmd = docker_base + [
        "run",
        "--rm",                              # delete container after exit
        "--network=none",                    # no internet
        f"--memory={DOCKER_MEMORY}",         # RAM cap
        f"--cpus={DOCKER_CPUS}",             # CPU cap
        "--security-opt", "no-new-privileges:true",  # no privilege escalation
        "-v", f"{wsl_workspace}:/workspace:rw",  # workspace mount
        "--workdir", "/workspace",           # start inside workspace
        DOCKER_IMAGE,
    ] + _get_install_cmd("/workspace")

    logger.info(
        "docker_sandbox.starting",
        image=DOCKER_IMAGE,
        workspace=str(workspace),
        wsl_path=wsl_workspace,
        timeout_s=timeout,
    )

    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=timeout,
        )
        output = result.stdout + result.stderr
        rc     = result.returncode

        logger.info(
            "docker_sandbox.completed",
            returncode=rc,
            output_lines=output.count("\n"),
            status="passed" if rc == 0 else "failed",
        )
        return rc, output

    except subprocess.TimeoutExpired:
        logger.error(
            "docker_sandbox.timeout",
            timeout_s=timeout,
            hint="Increase DOCKER_SANDBOX_TIMEOUT or optimise the test suite",
        )
        return 1, f"[SANDBOX TIMEOUT] Tests exceeded {timeout}s limit and were killed."

    except FileNotFoundError:
        logger.error(
            "docker_sandbox.not_found",
            cmd=DOCKER_CMD,
            hint="Ensure Docker is running and 'wsl docker' works from PowerShell",
        )
        return 1, f"[SANDBOX ERROR] Docker command '{DOCKER_CMD}' not found."

    except Exception as exc:
        logger.error("docker_sandbox.error", error=str(exc))
        return 1, f"[SANDBOX ERROR] {exc}"