"""
PRGeneer — Agent Node #7

Responsibility:
    Open a Pull Request on GitHub using the PyGithub library.
    Builds a structured PR description from the pipeline state.

Design decisions:
    - PyGithub (not subprocess git commands) — safe, no shell injection.
    - Duplicate PR detection: if a PR already exists for the branch, the node
      returns its URL rather than creating a duplicate.
    - PR description is templated from state — no LLM call needed here
      (the data is already structured).
    - Draft PR flag is always False — PRs are ready for review by default.
    - If tests were PARTIAL (failed in report mode), the PR description clearly
      states this so reviewers are not surprised.

LangGraph contract:
    Input  : AgentState  (reads parsed_task, repo_analysis, code_change,
                          test_result, feature_branch, commit_sha)
    Output : dict        (sets pull_request, status, step_logs)
"""

from __future__ import annotations

import os
import re
from datetime import datetime, timezone
from typing import Any

from github import Github, GithubException

from app.models.state import AgentState, PipelineStatus, PullRequest, TestStatus
from app.utils.logger import get_logger

logger = get_logger(__name__)

GITHUB_TOKEN = os.getenv("GITHUB_TOKEN", "")


# ─────────────────────────────────────────────────────────────────────────────
# Repo slug extractor
# ─────────────────────────────────────────────────────────────────────────────

def _extract_repo_slug(url: str) -> str:
    """
    Extract 'owner/repo' from a GitHub URL.
    Handles trailing .git and trailing slashes.
    """
    match = re.search(r"github\.com[/:]([^/]+/[^/]+?)(?:\.git)?/?$", url)
    if not match:
        raise ValueError(f"Cannot extract repo slug from URL: {url!r}")
    return match.group(1)


# ─────────────────────────────────────────────────────────────────────────────
# PR body builder
# ─────────────────────────────────────────────────────────────────────────────

def _build_pr_body(state: AgentState) -> str:
    task     = state.parsed_task
    analysis = state.repo_analysis
    change   = state.code_change
    test     = state.test_result

    # Test result block
    if test:
        test_icon   = "✅" if test.status == TestStatus.PASSED else "❌"
        test_block  = (
            f"## Test Result\n"
            f"**Command:** `{test.command}`  \n"
            f"**Status:** {test_icon} {test.status.value.upper()}  \n"
            f"**Duration:** {test.duration_seconds}s  \n"
        )
        if test.retry_count:
            test_block += f"**Retries:** {test.retry_count}  \n"
        if test.status != TestStatus.PASSED:
            test_block += (
                f"\n> ⚠️ Tests did not pass. Please review before merging.\n\n"
                f"<details><summary>Test output</summary>\n\n"
                f"```\n{test.output[:1500]}\n```\n</details>\n"
            )
    else:
        test_block = "## Test Result\n_Tests were not run._\n"

    # Changed files block
    changed_files = change.changed_files if change else []
    files_block = "\n".join(f"- `{f}`" for f in changed_files) or "_No files recorded._"

    # Acceptance criteria block
    criteria = task.acceptance_criteria if task else []
    criteria_block = "\n".join(f"- {c}" for c in criteria) or "_None specified._"

    # AI usage block
    ai_block = ""
    if change:
        ai_block = (
            f"## AI Usage\n"
            f"**Model:** `{change.model_used}`  \n"
            f"**Prompt tokens:** {change.prompt_tokens}  \n"
            f"**Completion tokens:** {change.completion_tokens}  \n\n"
            f"**Changed files:**\n{files_block}\n"
        )

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    return f"""## Summary
{task.requirement if task else 'N/A'}

## Task
**ID:** {task.task_id if task else 'N/A'}

## Acceptance Criteria
{criteria_block}

## Stack
**Language:** {analysis.language if analysis else 'N/A'}  
**Framework:** {analysis.framework if analysis else 'N/A'}  
**Test command:** `{analysis.test_command if analysis else 'N/A'}`

{test_block}
{ai_block}
---
> 🤖 Generated by **AI Development Agent** on {now}
"""


# ─────────────────────────────────────────────────────────────────────────────
# LangGraph node entry point
# ─────────────────────────────────────────────────────────────────────────────

def run(state: AgentState) -> dict[str, Any]:
    """LangGraph node. Reads pipeline state, creates GitHub PR."""
    state.log_step("pr_agent", "started")
    logger.info("pr_agent.started", branch=state.feature_branch)

    if not state.feature_branch or not state.parsed_task:
        msg = "pr_agent: feature_branch or parsed_task missing"
        logger.error("pr_agent.missing_input")
        state.log_step("pr_agent", "failed", detail=msg)
        return {"status": PipelineStatus.FAILED, "error": msg, "step_logs": state.step_logs}

    if not GITHUB_TOKEN:
        msg = "pr_agent: GITHUB_TOKEN is not set"
        logger.error("pr_agent.no_token")
        state.log_step("pr_agent", "failed", detail=msg)
        return {"status": PipelineStatus.FAILED, "error": msg, "step_logs": state.step_logs}

    task = state.parsed_task

    # ── Extract repo slug ─────────────────────────────────────────────────
    try:
        slug = _extract_repo_slug(task.repository_url)
    except ValueError as exc:
        msg = str(exc)
        logger.error("pr_agent.bad_repo_url", error=msg)
        state.log_step("pr_agent", "failed", detail=msg)
        return {"status": PipelineStatus.FAILED, "error": msg, "step_logs": state.step_logs}

    # ── GitHub client ─────────────────────────────────────────────────────
    gh   = Github(GITHUB_TOKEN)
    repo = gh.get_repo(slug)

    pr_title = f"{task.task_id} {task.title}"
    pr_body  = _build_pr_body(state)
    base     = task.base_branch
    head     = state.feature_branch

    # ── Duplicate PR detection ────────────────────────────────────────────
    existing = list(repo.get_pulls(state="open", head=f"{slug.split('/')[0]}:{head}"))
    if existing:
        pr = existing[0]
        logger.warning("pr_agent.duplicate_pr", number=pr.number, url=pr.html_url)
        state.log_step("pr_agent", "completed",
                       detail=f"existing PR #{pr.number} reused: {pr.html_url}")
        return {
            "pull_request": PullRequest(
                number=pr.number, url=pr.html_url,
                title=pr.title, branch=head,
            ),
            "status": PipelineStatus.SUCCESS,
            "step_logs": state.step_logs,
        }

    # ── Create PR ─────────────────────────────────────────────────────────
    try:
        pr = repo.create_pull(
            title=pr_title,
            body=pr_body,
            base=base,
            head=head,
            draft=False,
        )
        logger.info("pr_agent.created", number=pr.number, url=pr.html_url)
    except GithubException as exc:
        msg = f"pr_agent: GitHub API error: {exc.status} {exc.data}"
        logger.error("pr_agent.create_failed", error=msg)
        state.log_step("pr_agent", "failed", detail=msg)
        return {"status": PipelineStatus.FAILED, "error": msg, "step_logs": state.step_logs}

    state.log_step("pr_agent", "completed",
                   detail=f"PR #{pr.number}: {pr.html_url}")

    final_status = (
        PipelineStatus.SUCCESS
        if state.status != PipelineStatus.PARTIAL
        else PipelineStatus.PARTIAL
    )

    return {
        "pull_request": PullRequest(
            number=pr.number,
            url=pr.html_url,
            title=pr_title,
            branch=head,
        ),
        "status": final_status,
        "step_logs": state.step_logs,
    }