"""
PRGeneer — Agent Node #7

Responsibility:
    Open a Pull Request on GitHub using the PyGithub library.
    Builds a structured PR description matching the challenge spec exactly.

PR body sections (per challenge doc 4.7):
    ## Summary
    ## Task
    ## Changes          ← was missing, now added
    ## Test Result
    ## AI Usage
    ## Generated By

Design decisions:
    - PyGithub only — no shell injection risk.
    - Duplicate PR detection: existing open PR for the same branch is reused.
    - Test command displayed without internal pytest flags (--rootdir etc.).
    - Draft PR flag is always False — PRs are ready for review by default.

LangGraph contract:
    Input  : AgentState  (reads parsed_task, repo_analysis, code_change,
                          test_result, feature_branch, commit_sha)
    Output : dict        (sets pull_request, status, step_logs)
"""

from __future__ import annotations

import os
import re
from datetime import datetime, timezone
from typing import Any

from github import Github, GithubException

from app.models.state import AgentState, PipelineStatus, PullRequest, TestStatus
from app.providers.git_provider import get_git_provider
from app.utils.logger import get_logger

logger = get_logger(__name__)

GITHUB_TOKEN = os.getenv("GITHUB_TOKEN", "")


# ─────────────────────────────────────────────────────────────────────────────
# Repo slug extractor
# ─────────────────────────────────────────────────────────────────────────────

def _extract_repo_slug(url: str) -> str:
    """Extract 'owner/repo' from a GitHub URL. Handles .git suffix and slashes."""
    match = re.search(r"github\.com[/:]([^/]+/[^/]+?)(?:\.git)?/?$", url)
    if not match:
        raise ValueError(f"Cannot extract repo slug from URL: {url!r}")
    return match.group(1)


# ─────────────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────────────

def _clean_test_command(raw_command: str) -> str:
    """
    Strip internal pytest flags from the displayed command.
    --rootdir=... and --override-ini=... are implementation details,
    not meaningful to a human reviewer.
    """
    cmd = re.sub(r" --rootdir=\S+", "", raw_command)
    cmd = re.sub(r" --override-ini=\S+", "", cmd)
    return cmd.strip()


def _changes_block(change) -> str:
    """
    Build the ## Changes bullet list from code_change.
    Describes what was done based on the changed file list.
    """
    if not change or not change.changed_files:
        return "_No changes recorded._"

    bullets: list[str] = []
    for f in change.changed_files:
        name = f.split("/")[-1]
        if re.search(r"(test_|_test\.|Test\.|\.test\.|\.spec\.)", f):
            bullets.append(f"Added or updated unit tests in `{name}`")
        else:
            bullets.append(f"Modified `{name}` to implement the required change")
    return "\n".join(f"- {b}" for b in bullets)


# ─────────────────────────────────────────────────────────────────────────────
# PR body builder — matches challenge doc §4.7 exactly
# ─────────────────────────────────────────────────────────────────────────────

def _build_pr_body(state: AgentState) -> str:
    task     = state.parsed_task
    analysis = state.repo_analysis
    change   = state.code_change
    test     = state.test_result

    # ── Summary ──────────────────────────────────────────────────────────
    summary = task.requirement if task else "N/A"

    # ── Task ─────────────────────────────────────────────────────────────
    task_id = task.task_id if task else "N/A"

    # ── Acceptance Criteria ───────────────────────────────────────────────
    criteria = task.acceptance_criteria if task else []
    criteria_block = "\n".join(f"- {c}" for c in criteria) or "_None specified._"

    # ── Changes ───────────────────────────────────────────────────────────
    changes_block = _changes_block(change)

    # ── Test Result ───────────────────────────────────────────────────────
    if test:
        test_icon    = "✅" if test.status == TestStatus.PASSED else "❌"
        clean_cmd    = _clean_test_command(test.command)
        test_block   = (
            f"**Command:** `{clean_cmd}`  \n"
            f"**Status:** {test_icon} {test.status.value.upper()}  \n"
            f"**Duration:** {test.duration_seconds}s"
        )
        if test.retry_count:
            test_block += f"  \n**Retries:** {test.retry_count}"
        if test.status != TestStatus.PASSED:
            test_block += (
                f"\n\n> ⚠️ Tests did not pass. Please review before merging.\n\n"
                f"<details><summary>Test output</summary>\n\n"
                f"```\n{test.output[:1500]}\n```\n</details>"
            )
    else:
        test_block = "_Tests were not run._"

    # ── AI Usage ──────────────────────────────────────────────────────────
    if change:
        changed_files_list = "\n".join(f"- `{f}`" for f in change.changed_files)
        ai_block = (
            f"**Model:** `{change.model_used}`  \n"
            f"**Prompt tokens:** {change.prompt_tokens}  \n"
            f"**Completion tokens:** {change.completion_tokens}  \n\n"
            f"**Changed files:**\n{changed_files_list}"
        )
    else:
        ai_block = "_No AI usage recorded._"

    # ── Stack info ────────────────────────────────────────────────────────
    lang      = analysis.language if analysis else "N/A"
    framework = analysis.framework if analysis else "N/A"
    test_cmd  = _clean_test_command(analysis.test_command) if analysis else "N/A"

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    # Diff preview section
    if state.diff_preview:
        diff_section = (
            f"<details><summary>View diff ({state.diff_preview.count(chr(10))} lines)</summary>\n\n"
            f"```diff\n{state.diff_preview}\n```\n</details>"
        )
    else:
        diff_section = "_Diff not available._"

    return f"""## Summary
{summary}

## Task
**ID:** {task_id}

## Acceptance Criteria
{criteria_block}

## Changes
{changes_block}

## Stack
**Language:** {lang}  
**Framework:** {framework}  
**Test command:** `{test_cmd}`

## Test Result
{test_block}

## AI Usage
{ai_block}

## Diff Preview
{diff_section}

## Generated By
> 🤖 **AI Development Agent** — {now}
"""


# ─────────────────────────────────────────────────────────────────────────────
# LangGraph node entry point
# ─────────────────────────────────────────────────────────────────────────────

def run(state: AgentState) -> dict[str, Any]:
    """LangGraph node. Reads pipeline state, creates GitHub PR."""
    state.log_step("pr_agent", "started")
    logger.info("pr_agent.started", branch=state.feature_branch)

    if not state.feature_branch or not state.parsed_task:
        msg = "pr_agent: feature_branch or parsed_task missing"
        logger.error("pr_agent.missing_input")
        state.log_step("pr_agent", "failed", detail=msg)
        return {"status": PipelineStatus.FAILED, "error": msg, "step_logs": state.step_logs}

    # ── Dry-run: skip PR creation ────────────────────────────────────────
    if state.dry_run:
        logger.info("pr_agent.dry_run_skip", branch=state.feature_branch)
        state.log_step("pr_agent", "completed",
                       detail="[DRY-RUN] PR not created — dry_run=true")
        return {
            "status":     PipelineStatus.SUCCESS,
            "step_logs":  state.step_logs,
        }

    task = state.parsed_task

    # ── Git provider (abstracted — supports GitHub today, GitLab/Bitbucket later)
    try:
        provider = get_git_provider()
        slug     = provider.get_repo_slug(task.repository_url)
    except (ValueError, RuntimeError) as exc:
        msg = str(exc)
        logger.error("pr_agent.provider_error", error=msg)
        state.log_step("pr_agent", "failed", detail=msg)
        return {"status": PipelineStatus.FAILED, "error": msg, "step_logs": state.step_logs}

    pr_title = f"{task.task_id} {task.title}"
    pr_body  = _build_pr_body(state)
    head     = state.feature_branch

    # ── Duplicate PR detection ────────────────────────────────────────────
    existing = provider.get_open_pull_request(slug, head)
    if existing:
        logger.warning("pr_agent.duplicate_pr", number=existing.number, url=existing.url)
        state.log_step("pr_agent", "completed",
                       detail=f"existing PR #{existing.number} reused: {existing.url}")
        return {
            "pull_request": PullRequest(
                number=existing.number, url=existing.url,
                title=existing.title, branch=head,
            ),
            "status": PipelineStatus.SUCCESS,
            "step_logs": state.step_logs,
        }

    # ── Create PR ─────────────────────────────────────────────────────────
    try:
        pr = provider.create_pull_request(
            repo_slug=slug,
            title=pr_title,
            body=pr_body,
            head=head,
            base=task.base_branch,
            draft=False,
        )
        from app.utils.audit import audit
        audit("pr.created",
              task_id=state.parsed_task.task_id if state.parsed_task else None,
              pr_number=pr.number, pr_url=pr.url, branch=head)
        logger.info("pr_agent.created", number=pr.number, url=pr.url)
    except RuntimeError as exc:
        msg = str(exc)
        logger.error("pr_agent.create_failed", error=msg)
        state.log_step("pr_agent", "failed", detail=msg)
        return {"status": PipelineStatus.FAILED, "error": msg, "step_logs": state.step_logs}

    state.log_step("pr_agent", "completed",
                   detail=f"PR #{pr.number}: {pr.url}")

    final_status = (
        PipelineStatus.SUCCESS
        if state.status != PipelineStatus.PARTIAL
        else PipelineStatus.PARTIAL
    )

    return {
        "pull_request": PullRequest(
            number=pr.number,
            url=pr.url,
            title=pr_title,
            branch=head,
        ),
        "status": final_status,
        "step_logs": state.step_logs,
    }